spring.application.name=treading-plateform

server.port=5454

# For MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/trading
spring.datasource.username=root
spring.datasource.password=9125
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abhinav97297@gmail.com
spring.mail.password=kuhj ltqx oidi egkf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

razorpay.api.key=rzp_test_wyqye1eHW4NHpv
razorpay.api.secret=GxOQEIK4hv1L3w4cdADBFqm6
stripe.api.key=sk_test_51RTg1TGaGNvNDZ6qXNmoTQHYhIbnyoINlmlNqxp3DXlXGnRX7WVb6Ak1RlT7Z9MnTX8Tq6QQXy7zCd6pKZhG7sFV00Cby2CbIB

# coingecko api key
coingecko.api.key=CG-DWLBCyJqeKM4fdQm1ScpPunA

# gemini api key
gemini.api.key=AIzaSyCkzaNTfgONq8E633KtYX-Kvmsn0aNnNgY

#google oauth2 (optional)
spring.security.oauth2.client.registration.google.client-id=your id
spring.security.oauth2.client.registration.google.client-secret=your secret

